title: False Flag
email: rjcoupe@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  Cybersecurity notes and thoughts, exploring events and news from the internet with a view to making them accessible to those on the edge of or even outside the industry
url: https://falseflag.blog # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-dash
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-mentions

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

paginate: 5